language: c
sudo: false

cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
    - ARDUINO_IDE_VERSION="1.8.9"
    - PRETTYNAME="Adafruit SPIFlash library"

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
  - arduino --install-library "Adafruit NeoPixel","SdFat"
  - pip3 install --user adafruit-nrfutil

before_script:
  - sed -i 's/\(ENABLE_EXTENDED_TRANSFER_CLASS\s\+\)0/\11/' $HOME/Arduino/libraries/SdFat/src/SdFatConfig.h
  - sed -i 's/\(FAT12_SUPPORT\s\+\)0/\11/' $HOME/Arduino/libraries/SdFat/src/SdFatConfig.h 

script:
  - build_samd_platforms
  - build_nrf5x_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)